[options]
Architecture = auto
SigLevel = Required DatabaseOptional
ParallelDownloads = 5

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# ZFS-Support (optional — nur wenn archzfs-Repo verfügbar)
# [archzfs]
# Server = https://archzfs.com/$repo/$arch
